'''
Generate stylesheet for stimuli version 1
'''
def get_keyframe(index: int, rotation_angle: int) -> str:
    '''
    Get keyframe (rotation animation) for a particular interval

    :params:
    - index (int): interval number
    - rotation_angle (int): the angle to rotate the stimulus by, in degrees

    :return:
    - keyframe for a particular interval (str)
    '''
    return (
        f'\n'
        f'@keyframes spin-accelerate-{index} {{\n'
        f'    100% {{\n'
        f'        transform: rotate({rotation_angle}deg);\n'
        f'    }}\n'
        f'}}\n'
    )


def generate_v1_style(
    stylesheet_path: str,
    num_intervals: int,
    rotation_increase: int,
):
    '''
    Generate stylesheet for stimuli version 1

    :params:
    - stylesheet_path (str): path to stylesheet to be generated
    - num_intervals (int): number of times the animation should be played
    - rotation_increase (int): the increase in rotation at each interval, in degrees

    :return:
    - void (None)
    '''
    rotation_angle = 360

    with open(stylesheet_path, 'w') as stylesheet:
        header_comment = '/* This stylesheet is autogenerated by generate_v2_style.py */\n'
        stylesheet.write(header_comment)
        
        for interval in range(num_intervals + 1):

            keyframe = get_keyframe(interval, rotation_angle)
            stylesheet.write(keyframe)

            rotation_angle += rotation_increase


if __name__ == '__main__':
    stylesheet_path = '/home/burntice/0_repositories/HP3603/stylesheets/v1.css'

    generate_v1_style(
        stylesheet_path,
        num_intervals=30,
        rotation_increase=30,
    )
